// 영문 콘텐츠 — ko.js 와 같은 사실을 영어 case-study 문체로 쓴다 (원고: portfolio-research/content-v2.en.md)
const en = {
  lang: 'en',
  nav: {
    home: 'Intro',
    about: 'About',
    skills: 'Skills',
    projects: 'Projects',
    build: 'How I Build',
    langSwitchLabel: 'KO',
    koOnlyNote: 'Korean only',
  },
  hero: {
    headline: 'I turn repetitive operations work into AI systems that run every day',
    sub: "I'm Jinhee Mok, an AI Builder. For 10 months I was the only builder at StyleSeller, a social commerce startup. I designed, shipped, and ran its in-house AI operations system.",
    metrics: [
      { value: '10 mo', label: 'Solo builder · Dec 2025–now' },
      { value: '7,000', label: 'My commits (5 core repos)' },
      { value: '~40', label: 'Services in production' },
      { value: '4,500+', label: 'Automated test cases' },
    ],
  },
  systemMap: {
    title: 'System Map',
    intro:
      'This started as Instagram DM automation and grew into three core repositories: brand-tool, email-agent, and styleseller-agent-company. Today they run as one system. Staff work in a single web app. Behind it, agents and employee-PC workers share the same databases and the same knowledge graph. Click a number to open that case study.',
    image: '/images/v2/system-map-en.png',
    imageAlt: 'StyleSeller AI operations system map',
    nodes: [
      { id: 'vendor-cs', label: '① Vendor Support AI', caseId: 'vendor-cs' },
      { id: 'sales-pipeline', label: '② Sales Pipeline', caseId: 'sales-pipeline' },
      { id: 'company-os', label: '③ AI Company OS · Spark', caseId: 'company-os' },
      { id: 'email-agent', label: '④ CEO Email Agent', caseId: 'email-agent' },
      { id: 'field-fleet', label: '⑤ Field Fleet · Platform Ops', caseId: 'field-fleet' },
    ],
    layers: [
      { name: 'People', desc: 'Internal ops web app, Slack approval cards, Chrome extension panels' },
      { name: 'Agents', desc: 'AI Company OS on Paperclip — issues and approvals, plus vendor-support and content agents' },
      { name: 'Knowledge', desc: 'GraphRAG (LightRAG + Neo4j). 13 workspaces shared by email, vendor support, Spark, and vendor matching' },
      { name: 'Edge', desc: 'KakaoTalk CLI, real-time relays, seller-finder workers, and extensions on staff Macs and PCs. One-line install, auto-update' },
      { name: 'Data & infra', desc: 'GCP VM, ~40 Docker Compose services, 6 self-hosted Postgres DBs + PostgREST, LiteLLM, Langfuse' },
    ],
  },
  cases: [
    {
      id: 'vendor-cs',
      slug: 'vendor-cs',
      logo: '/images/v2/logo10.png',
      title: 'Vendor Support AI — capture, answer, and escalate supplier chats on KakaoTalk',
      shortTitle: 'Vendor Support AI',
      period: 'Jun 2026 – present',
      role: 'Design, build, operate (solo)',
      repos: 'styleseller-agent-company (vendor agent, chatbot, CS Copilot) · styleseller-kakaocli (Swift)',
      oneLiner: 'Supplier questions arrive in KakaoTalk, a messenger with no public API. This system collects them in real time, answers with evidence, and hands off to a person when unsure.',
      highlights: [
        'Real-time chat capture on employee PCs: a Swift CLI that watches local data changes, plus Mac/Windows relays',
        'Agentic-RAG chatbot: a tool-calling loop plus evidence, persona, and turn-taking judges',
        'Human-in-the-loop: unknown questions go to the owner as Slack cards, and human edits are learned back',
        'Ops outputs: per-vendor ledgers (Sheets/Drive), morning and evening digests, a vendor knowledge wiki, contract-term extraction',
      ],
      stack: ['Python', 'FastAPI', 'Swift (macOS)', 'Node.js', 'Chrome Extension MV3', 'LightRAG + Neo4j', 'MCP', 'LiteLLM', 'Gemini · Claude', 'Postgres + PostgREST', 'Slack API', 'Google Sheets · Drive API'],
      scale: [
        'Vendor agent backend: 61K lines · 600 commits · 107 test files',
        'Chatbot service: 806 commits (485 in the chatbot modules)',
        'CS Copilot extension + local sender: 631 commits',
        'KakaoTalk CLI fork: 81 of my commits · Swift 3.9K → 6.6K lines',
      ],
      background:
        "StyleSeller's supplier (vendor) questions arrived in employees' personal KakaoTalk. The same question got different answers depending on who replied, and the history lived only on each person's PC. " +
        'KakaoTalk has no public API for personal chats, so a server alone could not solve this. I split the work three ways: employee PCs collect the chats, agents on the server draft the answers, and people make the judgment calls at clearly defined points.',
      flow: [
        "A Swift CLI detects KakaoTalk data changes on an employee's Mac and sends webhooks. A separate collector does the same on Windows PCs.",
        'The vendor agent runs an allowlist gate, links the chat room to the internal vendor record, and ingests the raw text into the knowledge graph.',
        'The chatbot agent calls knowledge-graph, product, price, and proposal tools to draft an answer. The draft is queued only if it passes the judges.',
        'Hard questions go to the owner as a Slack card. Edited answers are learned back into the graph.',
        'An employee Mac claims the send job, sends it through the KakaoTalk CLI, and confirms delivery.',
      ],
      architectureImages: [{ src: '/images/v2/vendor-cs-en.png', alt: 'Vendor Support AI flow' }],
      troubleshooting: [
        {
          title: "Answering vendor A with vendor B's terms (RAG leakage)",
          problem: "A 30-question smoke test caught the bot quoting another vendor's private deal terms as company policy.",
          cause: 'The knowledge graph structure, not chat history: private deals were retrieved alongside shared knowledge.',
          action: "Added tool-level redaction of other vendors' private deals, plus an answer-scope gate.",
          result: 'This layer sits on top of the per-vendor/shared workspace split, so mixed retrieval results no longer leak into answers.',
        },
        {
          title: '21% of send jobs failed permanently',
          problem: '31 of 147 KakaoTalk send jobs never finished.',
          cause: 'An Accessibility call that checks the window state could hang forever.',
          action: 'Added a hard-timeout watchdog, and verified actual delivery after each send.',
        },
        {
          title: 'A keyword filter silently dropped messages',
          problem: 'A regex gate blocked messages before they reached the LLM, and nobody noticed.',
          action: 'Replaced it with a cheap trigger followed by a 5-second, temperature-0 LLM judge. The judge fails closed and shows its reason to staff.',
        },
        {
          title: 'Empty answers during Claude outages',
          problem: 'When Claude auth failed and traffic fell back to Gemini, answers came back empty.',
          action: "Restored multi-turn function calling in the Gemini proxy: tool_calls restoration, tool_call_id mapping, and aligned timeouts.",
        },
        {
          title: 'Zero-loss capture',
          problem: 'A dropped connection between an employee PC and the server could lose messages.',
          action: 'The local checkpoint advances atomically only after the server acknowledges. Stalls alert Slack.',
        },
      ],
      aiCollab: [
        'Evals: a 30-question smoke set caught the leakage, and judge tests live in the suite.',
        "Status: capture, ledgers, digests, and escalation run on 11 staff members' KakaoTalk. Auto-replies ran in real vendor rooms in August. An improved version is now being validated in a test vendor room.",
        'Judgment stays with people: unknown questions and anything about prices or contracts go through the owner.',
      ],
    },
    {
      id: 'sales-pipeline',
      slug: 'sales-pipeline',
      logo: '/images/logo7.png',
      title: 'Sales Pipeline — from seller discovery to tailored outreach and vendor matching (brand-tool)',
      shortTitle: 'Sales Pipeline',
      period: 'Mar 2026 – present',
      role: 'Full-stack build and operate (solo; every brand-tool commit is mine)',
      repos: 'brand-tool (Next.js) · styleseller-agent-company (PC workers, send workers) · email-agent (knowledge graph)',
      oneLiner: 'Finds Instagram sellers automatically, sends each one KakaoTalk product cards that match their sales history, and uses an LLM to recommend suppliers for new products.',
      highlights: [
        'Seller Finder: hashtag rules → distributed workers on employee PCs → per-rule scorecards → sheet mirror',
        "Tailored KakaoTalk campaigns: product cards matched to each seller's sales history, scheduled over channel and personal chats, with a reply inbox and opt-out handling",
        'Vendor matching: knowledge-graph search ∪ category candidates → LLM judgment → outcome tracking',
        'Generated proposal PDF/XLSX files and a chat assistant for editing proposals',
      ],
      stack: ['Next.js 16', 'React 19', 'TypeScript', 'Tailwind CSS 4', 'Postgres 16 + PostgREST', 'Vertex AI Gemini 2.5', 'Playwright', 'Node.js workers', 'n8n', 'Vitest', 'Docker', 'GitHub Actions'],
      scale: [
        'brand-tool: 1,502 commits · 134 API routes · 33 screens',
        '130 DB migrations · 205 test files',
        'Seller Finder (server + worker) 24K lines · KakaoTalk campaigns 34K lines, 470 commits',
      ],
      background:
        'To build one proposal, sales staff jumped between Google Sheets, an external CRM, and Notion, and calculated prices by hand. Seller discovery meant clicking through hashtags one at a time to build a list. ' +
        'I started by consolidating the data into one database, then expanded the app until discovery, outreach, and matching all happened in one place.',
      flow: [
        'Staff create hashtag rules. The server creates a run and assigns it to worker PCs.',
        'Workers use browser automation to report sellers who pass the filters (reel views, captions, and so on).',
        'Results merge into a seller ledger that combines Notion, the KakaoTalk ledger, and Seller Finder. Operators pick targets and schedule a campaign.',
        'A browser worker on the VM sends channel messages, and a Mac KakaoTalk CLI sends personal chats. Replies are collected and judged in an inbox.',
        'For a new product, the LLM recommends suppliers from the combined graph and category candidates. Proposal chats go out through a send queue.',
      ],
      architectureImages: [{ src: '/images/v2/sales-pipeline-en.png', alt: 'Sales pipeline flow' }],
      troubleshooting: [
        {
          title: "Collection didn't work from servers",
          problem: 'Instagram collection was blocked from datacenter environments.',
          action: "Designed a distributed worker that runs on employee PCs. It uses browser automation without clicking, so it never interrupts the employee's work. The server owns the job queue, device-key registration, one-account-per-PC, and stall diagnosis/reassignment.",
          result: 'Worker PCs never hold DB keys, only revocable device keys. Nine worker PCs are in service.',
        },
        {
          title: 'Recovery cancelled every running job',
          problem: 'When the server came back after an outage, its first cleanup cancelled all six runs in progress.',
          cause: 'The rule "cancel jobs of workers unseen for 3 min" counted server downtime as worker absence.',
          action: 'The cleanup function now records its own run interval. It treats gaps as server outage and cancels only after 3 min of continuous uptime.',
          result: 'In a psql reproduction, the old function cancelled 2/2 and the new one cancelled 0.',
        },
        {
          title: 'Yield displayed 3× too low',
          problem: 'Seller Finder yield showed 1.4%.',
          cause: 'Resuming a run reset only the numerator.',
          action: 'Filtered by the invariant denominator = numerator + rest instead of trusting the status field.',
          result: 'Real yield was 4.2%.',
        },
        {
          title: 'The reply inbox vanished on big send days',
          cause: 'A 3.5KB request URL with 200 room IDs hit a 502 at the proxy.',
          action: 'Measured the boundary (100 IDs OK, 200 failed) and chunked the IDs into groups of 60.',
        },
        {
          title: 'Non-deterministic LLM vendor matches',
          cause: 'Across chunks of 30, the same vendor got different scores and the last one overwrote the rest. The model also sometimes dropped items.',
          action: 'Kept the max score, re-queried only the missing items, and built candidates as the union of graph and category results.',
        },
      ],
      aiCollab: [
        'Production numbers: about 510 accounts screened per run at about a 4.4% pass rate; 261 recipients in a single campaign.',
        'The product cache syncs 3×/day. Ratio and absolute-floor guards stop a partial failure from marking the whole catalog as discontinued.',
        'Every feature went through a design spec, a plan, tests first, implementation, then review.',
      ],
    },
    {
      id: 'company-os',
      slug: 'company-os',
      logo: '/images/logo6.png',
      title: 'AI Company OS & Spark — an in-house AI org where humans approve',
      shortTitle: 'AI Company OS · Spark',
      period: 'May 2026 – present',
      role: 'Design, build, infra, operate (solo)',
      repos: 'styleseller-agent-company (server, MCP, services) · brand-tool (Spark and approvals UI)',
      oneLiner: 'I built a company-specific agent org and an internal assistant, Spark, on top of open-source Paperclip (issues, approvals, budgets).',
      highlights: [
        'Agent org: about 20 support, content, campaign, and ad agents under a CEO agent; the support and content agents run daily',
        'Spark: an internal assistant that cites its sources. It queries 4 databases read-only, scoped to the user\'s role, and routes CEO-mode actions to an approval inbox',
        'MCP: built knowledge-graph search and platform-control servers, and integrated an open-source Google Workspace server',
        'Commerce research: a Spark request triggers review collection in an employee\'s Chrome extension, which returns a VOC analysis as XLSX/PDF',
      ],
      stack: ['TypeScript', 'Node.js / Express', 'React', 'PostgreSQL (Drizzle)', 'Python / FastAPI', 'MCP', 'LiteLLM', 'Gemini 2.5', 'Claude', 'LightRAG + Neo4j', 'Langfuse', 'n8n', 'Docker Compose', 'GitHub Actions', 'GCP'],
      scale: [
        '4,316 of my commits (excluding merges and upstream)',
        '46 service directories · 3 MCP servers · 2 plugins',
        '56 design specs · 98 implementation plans',
      ],
      background:
        'The original plan was a 5-layer stack with Temporal, LangGraph, LiteLLM, and MCP. On May 20, 2026 the platform was installed, but it had 0 registered agents. ' +
        'Instead of adding more infrastructure, I switched to wiring up what was already running: the email agent, the DM bots, and n8n.',
      flow: [
        'Work arrives as issues. n8n only triggers work; Claude Code agents handle anything that needs reasoning, and FastAPI services handle routine processing.',
        'Staff ask Spark in the internal web app. Spark answers with sources, using role-scoped read-only queries and knowledge-graph search.',
        'Proposed actions go to an approval inbox and run only after a person approves them.',
      ],
      architectureImages: [
        { src: '/images/v2/company-os-en.png', alt: 'AI Company OS architecture' },
        { src: '/images/proj6-2.png', alt: 'Agent org chart (Korean labels)' },
      ],
      troubleshooting: [
        {
          title: 'Dropped an over-designed stack for one that shipped',
          problem: 'The 5-layer plan was expensive to build, and on May 20 there were 0 registered agents.',
          action: 'Replaced Temporal with n8n triggers + issues and LangGraph with Claude Code agents, then wired in the assets that were already running.',
          result: 'About 20 agents were on the org chart within four months.',
        },
        {
          title: "Spark can't see data outside a user's role",
          action: 'The server recomputes roles from DB membership instead of trusting the request. SQL runs under a read-only role behind a safe-SELECT guard. Approvals are idempotent, and there is a kill switch.',
        },
        {
          title: 'Collecting 1,000 reviews was on track to take 100 minutes',
          cause: 'In a minimized window, timers were throttled to once per minute, so each 0.5 s wait became 60 s. That works out to 100 minutes per 1,000 reviews.',
          action: 'Moved the waits onto ticks driven by the service worker, which the throttling does not affect.',
          result: 'Measured: 1,000 reviews in 2 min 30 s.',
        },
        {
          title: 'Safe deploys with many AI sessions at once',
          action: 'Added a VM-wide deploy lock, refused deploys from uncommitted trees, recorded the last-built commit, and tested the deploy-target selection.',
        },
      ],
      aiCollab: [
        'Evals: a Spark regression case set checks answer quality.',
        'Observability: LLM calls on the agent path go through LiteLLM and are traced in Langfuse.',
        'Design principle: irreversible actions such as refunds, VIP issues, and external contracts require human approval.',
      ],
    },
    {
      id: 'email-agent',
      slug: 'email-agent',
      logo: '/images/logo8.png',
      title: 'CEO Email Agent — GraphRAG drafts with human approval',
      shortTitle: 'CEO Email Agent',
      period: 'Mar – Jul 2026 (later grew into the company knowledge hub)',
      role: 'Design, build, deploy (solo)',
      repos: 'email-agent (FastAPI) · styleseller-agent-company (dashboard plugin, knowledge-mcp)',
      oneLiner: "Classifies incoming mail, finds evidence in the company knowledge graph, and drafts replies in the CEO's voice. Nothing is sent without human approval. The graph built here became the company's knowledge hub.",
      highlights: [
        'Gmail → n8n → FastAPI: parse → classify → draft → verify → learn',
        'LightRAG knowledge graph (Neo4j + pgvector), with an agentic query rewrite when coverage is thin',
        'LLM-as-judge verification plus sycophancy and parroting checks',
        'A style book learned from sent mail and human edits',
      ],
      stack: ['Python', 'FastAPI', 'asyncio', 'LightRAG', 'Neo4j', 'PostgreSQL + pgvector', 'Vertex AI Gemini 2.5', 'Claude', 'n8n', 'Slack', 'Docker Swarm', 'pytest', 'Pyright'],
      scale: [
        '923 commits (Mar–Jul 2026)',
        '~40K lines of Python · 25 API routers',
        'Knowledge-graph workspaces shared by email, vendor support, Spark, and vendor matching',
      ],
      background:
        "The CEO's inbox mixed brand partnerships, seller onboarding questions, and collaboration offers. Replies required past deal context, so they all landed on one person. " +
        'The goal was to have an evidence-backed draft ready, so a person only has to review it.',
      flow: [
        'n8n detects new mail and requests parsing and classification.',
        "The agent looks up the company, contact, and past requests in the graph, drafts a reply, and verifies it with an LLM judge.",
        'An approval request goes to Slack. Only approved drafts are saved to Gmail drafts.',
        'Sent mail is learned back into the style book and the graph.',
      ],
      architectureImages: [{ src: '/images/v2/email-agent-en.png', alt: 'CEO email agent pipeline' }],
      troubleshooting: [
        {
          title: 'Flat vector search missed past context',
          problem: 'Vector search alone could not answer "what did this company ask before?"',
          action: 'v2 moved to a LightRAG graph that links companies, contacts, and past requests.',
        },
        {
          title: 'The local reranker ate VM memory',
          action: 'Replaced the 2.2GB ONNX reranker with Vertex AI Gemini reranking.',
        },
        {
          title: 'Routine logistics confirmations were flagged as "parroting"',
          action: 'Added business-context exemptions to the judge prompt, and applied the same self-check to cold emails.',
        },
      ],
      aiCollab: [
        'Status: CEO auto-drafting was paused on 2026-09-02 as a business decision. Classification, learning, and the brand-mailbox drafting pipeline keep running.',
        'Spark and the vendor agent use the graph through knowledge-mcp, and brand-tool queries it directly for vendor matching.',
        'Definition of done: type hints on every function, zero Pyright errors, and every security review finding addressed.',
      ],
    },
    {
      id: 'field-fleet',
      slug: 'field-fleet',
      logo: '/images/logo9.png',
      title: "Field Fleet & Platform Ops — run on employee PCs what servers can't, safely",
      shortTitle: 'Field Fleet · Platform Ops',
      period: 'Feb 2026 – present',
      role: 'Extensions, CLI, installers, deploy pipeline, infra (solo)',
      repos: 'styleseller-agent-company (installers, relays, collectors, senders, deploy) · Instagram DM extension · brand-tool (deploy)',
      oneLiner: 'Ran Instagram and KakaoTalk work, which has no API, on employee PCs, and operated those PCs with one-line installs, auto-updates, and remote monitoring.',
      highlights: [
        'One-line installers for Mac and Windows, no admin rights needed, auto-update 3×/day',
        'Real-time KakaoTalk relay for 11 staff, a Windows KakaoTalk collector, automated group-buy announcements to open chats',
        'Instagram DM Chrome extension (Feb–Jul 2026): trusted input via CDP, multi-step send fallback, a daily self-check agent',
        'Infra: GCP VM, Docker Compose, 6 self-hosted Postgres DBs, GitHub Actions → registry deploys',
      ],
      stack: ['JavaScript / Node.js', 'Chrome Extension MV3', 'Chrome DevTools Protocol', 'Swift', 'Python', 'Bash', 'PowerShell', 'launchd', 'Playwright', 'Docker', 'nginx', 'GitHub Actions', 'GCP'],
      scale: [
        'PC delivery network: 689 commits',
        'Instagram DM extension + self-check: 26K lines',
        '11 staff on real-time KakaoTalk sync · 9 seller-finder worker PCs',
      ],
      background:
        "Instagram DMs and personal KakaoTalk have no public API. Staff copy-pasted the same messages, and the history lived only on each person's PC. " +
        'For work a server can\'t do, I turned employee PCs into automation nodes and built a way to deploy, update, and monitor them safely. On the server side, I ran about 40 services on one VM.',
      flow: [
        'Staff install the tools they need with one line. No admin rights required.',
        'Installed tools check for a new version 3×/day and update themselves.',
        'The server monitors each PC through job queues and status reports, and alerts Slack when one stalls.',
      ],
      architectureImages: [{ src: '/images/v2/field-fleet-en.png', alt: 'Field fleet and platform ops' }],
      troubleshooting: [
        {
          title: 'The cloud DB hit its egress quota',
          problem: 'Every API stopped when the cloud DB exceeded its egress quota.',
          action: 'Grepped the whole codebase to confirm the app only speaks the REST protocol, then stood up Postgres + PostgREST + nginx on the VM in the same shape.',
          result: 'Recovered the same day by swapping environment variables.',
        },
        {
          title: 'The hosting free tier was suspended',
          action: 'Restored service by moving 10 projects to a new team. Then built a VM deploy pipeline for the web app (GitHub Actions → registry → zero-downtime nginx swap) in 2 days.',
        },
        {
          title: 'Each deploy took 45–51 minutes',
          cause: 'The VM rebuilt a 6.3GB image every time.',
          action: 'Switched the VM to pulling CI-built images from a registry.',
          result: 'One deploy now takes about 11 minutes.',
        },
        {
          title: 'Open-chat sends failed silently for 3 days',
          cause: 'It was not a permissions problem. KakaoTalk was stuck without its main window, and there was no alerting path.',
          action: 'Added one retry after a sender restart, Slack alerts that include the failure reason, and a post-send watchdog cron.',
        },
        {
          title: 'A staff auth cookie anyone could forge by hand',
          action: 'Replaced it with a Web Crypto HMAC-signed, expiring cookie in edge middleware. It fails closed when the secret is missing.',
        },
        {
          title: 'A Windows worker crash-looped every 5 minutes',
          cause: 'A missing import inside an exception handler. Mocked tests stayed green.',
          action: 'Added a test that spawns the real process to check the wiring.',
          result: "Lesson: green tests don't mean correct wiring.",
        },
      ],
      aiCollab: [
        "For services without a public API, I checked terms of service and account safety first, and designed everything to run on a person's own account and PC, where that person can turn it on and off.",
        'Deploys are confirmed by the running code\'s hash, not the image date.',
      ],
    },
  ],
  howIBuild: {
    title: 'How I Build with AI',
    intro:
      'I build by orchestrating several Claude Code sessions in parallel. I decide what to build, how far to automate, and whether the result is right, and I verify it myself.',
    image: '/images/v2/build-loop-en.png',
    loopTitle: 'The loop',
    harnessTitle: 'Harness — turning agent mistakes into rules',
    loop: [
      { step: 'Design spec', desc: 'Problem, constraints, alternatives first. (56 written)' },
      { step: 'Plan', desc: 'Steps and how to verify each one. (98 written)' },
      { step: 'Tests first', desc: 'Write a reproduction test, then implement.' },
      { step: 'Cross-review', desc: 'Two agents from different sources review independently. A single adversarial pass has caught 6–9 real defects.' },
      { step: 'Real-device check', desc: 'Verify on real PCs and screens, then roll out in stages.' },
      { step: 'Confirm the deploy', desc: "Judge the deploy by the running code's hash." },
    ],
    harness: [
      'CLAUDE.md and rule files: done-gates for types, RLS, secrets, languages',
      '~100 incident notes so the same mistake does not repeat in the next session',
      'A pre-commit hook that blocks hand-rolled Windows bundles with line-ending drift',
      'A test-to-production write guard that blocked 17 tests able to reach production',
    ],
    incidentsTitle: 'Principles learned from incidents',
    incidents: [
      { title: "Green tests don't mean correct wiring", lesson: "Mocked tests don't catch a missing import. Keep a test that spawns the real process." },
      { title: 'Not finding it once ≠ absent', lesson: 'Before reporting that something is missing, recheck the time window, the target, and both ends of the pipe.' },
      { title: 'Judge by running code', lesson: "Confirm deploys by the running code's hash, not the image date." },
      { title: 'Compatible, not irreversible', lesson: 'Accept old and new formats side by side instead of doing one-way bulk rewrites.' },
      { title: "Switch off, don't delete", lesson: 'Count real usage first, then turn things off with a switch.' },
    ],
  },
  before: {
    title: 'Before · 2024–2025',
    intro: 'Same cards, smaller. Each one notes how it connects to what I do now. (These project pages are in Korean.)',
    projects: [
      {
        route: '/projects/project5',
        logo: '/images/logo5.png',
        title: 'We:Review',
        period: 'Aug–Oct 2025 · intern',
        oneLiner: 'OCR + LLM receipt verification',
        connection: '→ My first job moving repetitive review work to machines. It led straight to the ops automation at StyleSeller.',
      },
      {
        route: '/projects/project4',
        logo: '/images/logo4.png',
        title: 'FitChecker',
        period: 'Nov–Dec 2024',
        oneLiner: 'LangChain AI home-training chatbot (RAG recommendations)',
        connection: '→ My first RAG and agent work, and the starting point for knowledge-grounded agents.',
      },
      {
        route: '/projects/project3',
        logo: '/images/logo3.png',
        title: 'Briefify',
        period: 'Oct–Nov 2024',
        oneLiner: 'Image and document translate/summarize web service',
        connection: '→ My first LLM pipeline chaining several models.',
      },
      {
        route: '/projects/project1',
        logo: '/images/logo1.png',
        title: 'JeonJikSi',
        period: 'Aug–Oct 2024',
        oneLiner: 'Certification-based job listings web/app (Spring Boot · Flutter)',
        connection: '→ Team collaboration and backend fundamentals.',
      },
      {
        route: '/projects/project2',
        logo: '/images/logo2.png',
        title: 'Flux',
        period: 'Jul–Aug 2024',
        oneLiner: 'Artist auction platform, Market/My Page (Vue)',
        connection: '→ My first multi-screen state management, and the foundation for the internal ops web app.',
      },
    ],
  },
  about: {
    title: 'About Me',
    photo: '/images/img.jpg',
    tagline: "I'm Jinhee Mok, an AI Builder who turns repetitive work into AI systems that run every day.",
    paragraphs: [
      'I find the work people repeat in real operations, turn it into AI agents and automation, then ship and run it. My rule: machines take the repetition, people keep the judgment.',
      'At StyleSeller I spent 10 months as the only builder of the in-house AI operations system: a vendor-support agent, a sales platform from seller discovery to tailored outreach, an agent org with human approvals, and automation on employee PCs. I owned it from scoping to incident response.',
      "I build fast by orchestrating several Claude Code agents in parallel, and I verify the results with tests, cross-reviews, and real-device checks. After every incident, I turn the cause into a rule so it doesn't happen twice.",
      'Studying law, then working as an English instructor and a daycare operations manager, taught me to listen first to the people doing the work. That habit is how I choose what to automate.',
    ],
    experienceTitle: 'Journey',
    experienceLead: 'From a law degree to AI Builder',
    careerChangeLabel: 'Career Change',
    experience: [
      { period: '2025.12 – Present', org: 'StyleSeller · AI Builder (solo)', summary: 'Designed, built, and ran the in-house AI operations system', kind: 'tech' },
      { period: '2025.08 – 2025.10', org: 'We:Review (Welead) · Intern', summary: 'Built an OCR + LLM receipt-review pipeline on my own', kind: 'tech' },
      { period: '2025.05 – 2025.07', org: 'Korea IT Business Promotion Assoc.', summary: 'Generative AI developer program', kind: 'tech' },
      { period: '2024.10 – 2024.12', org: 'Hi-Media Academy · AI course', summary: 'AI projects with industry mentors (Briefify, FitChecker)', kind: 'tech' },
      { period: '2024.04 – 2024.10', org: 'Hi-Media Academy · Full-stack course', summary: 'Spring Boot and Vue.js team projects, collaboration, Git', kind: 'tech', careerChange: true },
      { period: '2022.06 – 2024.02', org: 'MonteKids · English Instructor', summary: 'Personalized lessons and self-directed learning', kind: 'pre' },
      { period: '2021.02 – 2023.06', org: 'Academic Credit Bank · Business Admin.', summary: 'Business administration degree program', kind: 'pre' },
      { period: '2021.03 – 2022.05', org: 'Pots&Pans · English Instructor', summary: 'Immersive lessons and progress tracking', kind: 'pre' },
      { period: '2018.08 – 2020.09', org: 'JLS · English Instructor', summary: 'Interactive lessons and parent communication', kind: 'pre' },
      { period: '2015.03 – 2018.02', org: 'Jeonwon Daycare · Operations Manager', summary: 'Team management and daily operations', kind: 'pre' },
      { period: '2008.03 – 2012.02', org: 'Cheongju University · B.A. in Law', summary: 'Law major', kind: 'pre' },
    ],
    nowTitle: 'Now',
    nowText: 'Validating the improved vendor auto-reply, raising Seller Finder targets, and strengthening ops observability.',
  },
  skills: {
    title: 'Skills',
    lead: 'What I have shipped with, from agents to deployment and operations.',
    groups: [
      {
        id: 'ai-agent',
        title: 'AI / Agent',
        items: [
          { id: 'llm-agent', label: 'Agentic RAG · tool-calling agents' },
          { id: 'mcp', label: 'MCP servers' },
          { id: 'rag', label: 'GraphRAG (LightRAG · Neo4j · pgvector)' },
          { id: 'litellm', label: 'LiteLLM model routing' },
          { id: 'langfuse', label: 'Langfuse observability' },
          { id: 'hitl', label: 'HITL approvals · LLM judges' },
          { id: 'claude-code', label: 'Claude Code multi-session' },
        ],
      },
      {
        id: 'backend',
        title: 'Backend',
        items: [
          { id: 'python', label: 'Python' },
          { id: 'fastapi', label: 'FastAPI' },
          { id: 'nextjs', label: 'Next.js' },
          { id: 'node', label: 'Node.js / Express' },
          { id: 'postgres', label: 'PostgreSQL / PostgREST' },
          { id: 'supabase', label: 'Supabase' },
          { id: 'java', label: 'Java' },
          { id: 'spring', label: 'Spring' },
          { id: 'mysql', label: 'MySQL' },
          { id: 'jpa', label: 'JPA' },
        ],
      },
      {
        id: 'frontend',
        title: 'Frontend',
        items: [
          { id: 'react', label: 'React' },
          { id: 'js', label: 'JavaScript' },
          { id: 'html', label: 'HTML' },
          { id: 'css', label: 'CSS' },
          { id: 'vue', label: 'Vue.js' },
          { id: 'flutter', label: 'Flutter' },
        ],
      },
      {
        id: 'devops',
        title: 'DevOps · Automation',
        items: [
          { id: 'docker', label: 'Docker' },
          { id: 'docker-compose', label: 'Docker Compose' },
          { id: 'gh-actions', label: 'GitHub Actions' },
          { id: 'gcp', label: 'GCP VM' },
          { id: 'nginx', label: 'nginx' },
          { id: 'zero-downtime', label: 'Zero-downtime deploys' },
          { id: 'git', label: 'Git' },
          { id: 'github', label: 'GitHub' },
          { id: 'n8n', label: 'n8n' },
          { id: 'chrome-ext', label: 'Chrome Extension MV3' },
          { id: 'playwright', label: 'Playwright / CDP' },
          { id: 'swift', label: 'Swift (macOS)' },
        ],
      },
    ],
  },
  legacyProjects: {
    project1: { title: 'JeonJikSi', route: '/projects/project1' },
    project2: { title: 'Flux', route: '/projects/project2' },
    project3: { title: 'Briefify', route: '/projects/project3' },
    project4: { title: 'FitChecker', route: '/projects/project4' },
    project5: { title: 'We:Review', route: '/projects/project5' },
  },
};

export default en;
