// 한국어 콘텐츠 — 수치는 git·운영 기록으로 검증한 값만 쓴다 (원고: portfolio-research/content-v2.ko.md)
const ko = {
  lang: 'ko',
  nav: {
    home: 'Intro',
    about: 'About',
    skills: 'Skills',
    projects: 'Projects',
    build: 'How I Build',
    langSwitchLabel: 'EN',
    koOnlyNote: '한국어만 제공',
  },
  hero: {
    headline: '현업의 반복 업무를, 매일 돌아가는 AI 시스템으로',
    sub: 'AI Builder 목진희입니다. SNS 커머스 스타트업 StyleSeller에서 10개월 동안 업무를 위한 사내 AI 운영 시스템을 혼자 설계·구축·운영했습니다.',
    metrics: [
      { value: '10개월', label: '1인 빌더 · 2025.12–현재' },
      { value: '7,000', label: '본인 커밋 (핵심 저장소 5개)' },
      { value: '~40', label: '운영 서비스 (Docker · GCP)' },
      { value: '4,500+', label: '자동 테스트 케이스' },
    ],
  },
  systemMap: {
    title: 'System Map',
    intro:
      '인스타그램 DM 자동화에서 시작해 핵심 저장소 세 개(brand-tool, email-agent, styleseller-agent-company)로 자랐고, 지금은 하나의 운영 시스템으로 맞물려 돌아갑니다. 직원은 웹 한 곳에서 일하고, 뒤에서는 에이전트와 직원 PC 워커가 같은 DB 와 같은 지식 그래프를 공유합니다. 번호를 누르면 해당 사례로 이동합니다.',
    image: '/images/v2/system-map-ko.png',
    imageAlt: 'StyleSeller AI 운영 시스템 전체 지도',
    nodes: [
      { id: 'vendor-cs', label: '① 벤더 CS AI', caseId: 'vendor-cs' },
      { id: 'sales-pipeline', label: '② 영업 파이프라인', caseId: 'sales-pipeline' },
      { id: 'company-os', label: '③ AI Company OS · Spark', caseId: 'company-os' },
      { id: 'email-agent', label: '④ 대표 메일 에이전트', caseId: 'email-agent' },
      { id: 'field-fleet', label: '⑤ 직원 PC 함대 · 운영 인프라', caseId: 'field-fleet' },
    ],
    layers: [
      { name: '사람 접점', desc: '사내 운영 웹, Slack 승인 카드, Chrome 확장 패널' },
      { name: '에이전트', desc: 'Paperclip 기반 AI Company OS — 이슈·승인, 벤더 CS·콘텐츠 에이전트' },
      { name: '지식', desc: 'GraphRAG(LightRAG + Neo4j) 워크스페이스 13개를 메일·벤더 CS·Spark·벤더 매칭이 공유' },
      { name: '현장', desc: '직원 맥·윈도우의 카톡 CLI·실시간 릴레이·셀러찾기 워커·확장, 한 줄 설치와 자동 갱신' },
      { name: '데이터·인프라', desc: 'GCP VM, Docker Compose 약 40개 서비스, 자체 호스팅 Postgres 6개 + PostgREST, LiteLLM, Langfuse' },
    ],
  },
  cases: [
    {
      id: 'vendor-cs',
      slug: 'vendor-cs',
      logo: '/images/v2/logo10.png',
      title: '벤더 CS AI — 카톡으로 오는 거래처(벤더) 문의를 모으고 근거로 답하는 에이전트',
      shortTitle: '벤더 CS AI',
      period: '2026.06 ~ 현재',
      role: '설계·개발·운영 (1인)',
      repos: 'styleseller-agent-company (벤더 에이전트·챗봇·CS Copilot) · styleseller-kakaocli (Swift)',
      oneLiner: '공식 API 가 없는 카카오톡의 벤더 문의를 실시간으로 모으고, 근거를 찾아 답하고, 이관·되묻기 없이 근거를 찾아 답합니다.',
      highlights: [
        '직원 PC 카톡 실시간 수집: 로컬 데이터 변경을 감지하는 Swift CLI + 맥·윈도우 릴레이',
        'Agentic RAG 챗봇: 도구 호출 루프 + 근거·페르소나·턴 판정 관문',
        '무조건 답변 정책(2026-09-02~): 이관·되묻기 없이 근거로 답하고, Slack 은 아침·저녁 요약과 직원 브리핑에 씁니다',
        '운영 산출물: 벤더별 대화 원장·시트·드라이브 보관, 아침·저녁 요약, 벤더 지식 위키, 계약 조건 추출',
      ],
      stack: ['Python', 'FastAPI', 'Swift (macOS)', 'Node.js', 'Chrome Extension MV3', 'LightRAG + Neo4j', 'MCP', 'LiteLLM', 'Gemini 2.5 Flash', 'Postgres + PostgREST', 'Slack API', 'Google Sheets · Drive API'],
      scale: [
        '벤더 에이전트 백엔드: 코드 6.1만 줄 · 커밋 600개 · 테스트 파일 107개',
        '챗봇 서비스: 커밋 806개 (챗봇 모듈 485개)',
        'CS Copilot 확장·로컬 발송 서버: 커밋 631개',
        '카톡 CLI 포크: 본인 커밋 81개 · Swift 3.9천 → 6.6천 줄',
      ],
      background:
        'StyleSeller 의 거래처(벤더) 문의는 담당 직원 개인 카카오톡으로 들어왔습니다. 같은 질문에도 사람마다 답이 달랐고, 대화 기록은 각자의 PC 에만 남았습니다. ' +
        '카카오톡 개인톡에는 공식 API 가 없어서 서버만으로는 풀 수 없었습니다. 직원 PC 에서 대화를 모으고, 서버의 에이전트가 답을 만들고, 사람이 판단할 지점을 분명히 나누는 구조로 풀었습니다.',
      flow: [
        '직원 맥의 카톡 데이터 변경을 Swift CLI 가 감지해 웹훅으로 보냅니다. 윈도우 PC 는 별도 수집기가 같은 일을 합니다.',
        '벤더 에이전트가 허용 목록 게이트를 통과시키고, 방 이름을 사내 벤더 레코드에 연결한 뒤 원문을 지식 그래프에 적재합니다.',
        '챗봇 에이전트가 지식 그래프·상품·가격·제안서 도구를 호출해 답을 만들고, 판정 관문을 통과해야만 발송 대기열에 올립니다.',
        '예외는 두 가지입니다. 다른 벤더 정보는 막고, 제안서를 보낼지 불분명하면 다시 확인합니다. 사람이 고친 답은 다시 지식 그래프에 학습됩니다.',
        '실제 발송은 직원 맥이 작업을 가져가 카톡 CLI 로 보내고, 도착까지 확인합니다.',
      ],
      architectureImages: [
        { src: '/images/v2/vendor-cs-ko.png', alt: '벤더 CS AI 흐름도' },
      ],
      troubleshooting: [
        {
          title: 'A 벤더 질문에 B 벤더 조건을 답한 문제 (RAG 교차 누출)',
          problem: '2026-08-13 운영 중에 다른 벤더의 개별 거래 조건을 회사 정책처럼 확답한 사례가 나왔습니다.',
          cause: '대화 기록이 아니라 지식 그래프 구조가 원인이었습니다. 개별 거래가 공용 지식과 함께 검색됐습니다.',
          action: '도구 단계에서 다른 벤더의 개별 거래 언급을 가리는 편집을 넣고, 답변 범위 게이트를 더했습니다.',
          result: '벤더 개별·공용 워크스페이스 분리 위에 한 겹을 더 둬서, 검색 결과가 섞여도 답변에는 새지 않게 했습니다.',
        },
        {
          title: '발송 작업의 21% 가 영구 실패한 문제',
          problem: '카톡 발송 작업 147건 중 31건이 끝나지 않고 실패로 남았습니다.',
          cause: '카톡 창 상태를 묻는 접근성 호출이 멈추면 작업이 영원히 대기했습니다.',
          action: '하드 타임아웃 워치독을 넣고, 발송 뒤 실제 도착 여부를 다시 확인하게 했습니다.',
        },
        {
          title: '키워드 필터가 메시지를 조용히 막던 문제',
          problem: '정규식 게이트가 메시지를 막고 LLM 을 건너뛰었습니다. 막힌 줄도 아무도 몰랐습니다.',
          action: '싼 1차 트리거 뒤에 temperature 0, 5초 제한 LLM 판정을 뒀습니다. 판정이 실패하면 닫히고(fail-closed), 이유가 직원 화면에 보입니다.',
        },
        {
          title: '메시지를 잃지 않는 수집',
          problem: '직원 PC 와 서버 사이 연결이 끊기면 메시지가 빠질 수 있었습니다.',
          action: '서버가 받았다고 응답한 뒤에만 로컬 체크포인트를 원자적으로 옮기고, 수집이 멈추면 Slack 으로 경보합니다.',
        },
      ],
      aiCollab: [
        '평가: 2026-08-13 운영 중 발견한 교차 누출을 막았고, 판정 관문 테스트를 스위트에 넣었습니다.',
        '운영 상태: 수집·원장·요약은 직원 PC 11대(맥 6·윈도우 5, 2026-09-16 등록)의 카톡으로 운영 중입니다. 자동 답변은 개선판을 테스트 벤더방에서 단계적으로 검증하고 있습니다.',
        '사람의 통제: 자동 답변은 테스트 방에서 단계적으로 검증 중이며, 테스트 방 한정 스위치·도구 승인·킬 스위치로 묶었습니다.',
      ],
    },
    {
      id: 'sales-pipeline',
      slug: 'sales-pipeline',
      logo: '/images/logo7.png',
      title: '영업 파이프라인 — 셀러 발굴부터 맞춤 발송·벤더 매칭까지 (사내 업무툴)',
      shortTitle: '영업 파이프라인',
      period: '2026.03 ~ 현재',
      role: '풀스택 개발·운영 (1인, brand-tool 커밋 전부 본인)',
      repos: 'brand-tool (Next.js) · styleseller-agent-company (직원 PC 워커·발송 워커) · email-agent (지식 그래프)',
      oneLiner: '인스타그램 셀러를 자동으로 찾고, 셀러마다 맞는 상품 카드를 카카오톡으로 보내고, 상품마다 공구를 열어 줄 판매 파트너사(벤더사)를 LLM 이 추천합니다.',
      highlights: [
        '셀러찾기: 해시태그 규칙 → 직원 PC 분산 워커 수집 → 규칙별 성적표 → 시트 미러',
        '맞춤카톡: 셀러별 판매 이력에 맞춘 상품 카드를 채널톡·개인톡으로 예약 발송, 답장함·거절 제외',
        '벤더 매칭: 지식 그래프 검색 ∪ 카테고리 후보 → LLM 판정 → 실제 성사 추적',
        '제안서 PDF·엑셀 자동 생성, 대화로 제안서를 고치는 챗봇',
      ],
      stack: ['Next.js 16', 'React 19', 'TypeScript', 'Tailwind CSS 4', 'Postgres 16 + PostgREST', 'Vertex AI Gemini 2.5', 'Playwright', 'Node.js 워커', 'n8n', 'Vitest', 'Docker', 'GitHub Actions'],
      scale: [
        'brand-tool: 커밋 1,502개 · API 라우트 134개 · 화면 33개',
        'DB 마이그레이션 130개 · 테스트 파일 205개',
        '셀러찾기(서버 + 워커) 코드 2.4만 줄 · 맞춤카톡 코드 3.4만 줄 · 커밋 470개',
      ],
      background:
        '영업 직원은 제안서 한 장을 만들려고 구글 시트·외부 CRM·노션을 오가며 가격을 손으로 계산했습니다. 셀러 발굴은 해시태그를 하나씩 눌러 리스트를 만드는 일이었습니다. ' +
        '흩어진 데이터를 한 DB 로 모으는 데서 시작해, 발굴·발송·매칭이 한 앱에서 끝나도록 넓혔습니다.',
      flow: [
        '직원이 해시태그 규칙을 만들면 서버가 회차를 만들어 직원 PC 워커에 배정합니다.',
        '워커가 브라우저 자동화로 조건(릴스 조회수·캡션 등)을 통과한 셀러를 찾아 보고합니다.',
        '결과는 셀러 원장(노션·카톡 원장·셀러찾기 병합)에 들어가고, 운영자가 대상을 골라 맞춤카톡을 예약합니다.',
        '채널톡은 VM 의 브라우저 워커가, 개인톡은 맥의 카톡 CLI 가 보냅니다. 답장은 다시 모아 답장함에서 판정합니다.',
        '상품을 올리면 지식 그래프와 카테고리 후보를 합쳐 LLM 이 공구를 열어 줄 판매 파트너사(벤더사)를 추천하고, 제안 카톡은 발송 큐로 나갑니다.',
      ],
      architectureImages: [
        { src: '/images/v2/sales-pipeline-ko.png', alt: '영업 파이프라인 흐름도' },
      ],
      troubleshooting: [
        {
          title: '서버에서는 수집할 수 없었던 문제',
          problem: '서버(데이터센터) 환경에서는 인스타그램 수집이 막혔습니다.',
          action: '직원 PC 에서 도는 분산 워커로 설계했습니다. 화면을 클릭하지 않는 브라우저 자동화라 직원 작업을 방해하지 않습니다. 서버는 잡 큐, 기기 키 등록, 한 계정 한 PC 규칙, 멈춘 회차 진단·재배치를 맡습니다.',
          result: '직원 PC 에는 DB 키를 주지 않고, 취소할 수 있는 기기 키만 줍니다. 워커 PC 9대가 운영 중입니다.',
        },
        {
          title: '서버가 살아나자마자 진행 중 회차를 모두 취소한 버그',
          problem: '서버가 멈췄다 복구되자 첫 정리 작업이 진행 중이던 회차 6개를 모두 취소했습니다.',
          cause: '"3분간 안 보인 워커의 작업 취소" 규칙이 서버가 꺼져 있던 시간까지 워커 부재로 셌습니다.',
          action: '정리 함수가 자기 실행 간격을 기록해, 간격이 비면 서버 부재로 보고 3분 연속 살아 있은 뒤에만 취소하게 했습니다.',
          result: 'psql 재현 테스트에서 옛 함수는 2/2 취소, 새 함수는 0 이었습니다.',
        },
        {
          title: '화면 수율이 실제보다 3배 낮게 보인 문제',
          problem: '셀러찾기 수율이 1.4% 로 보였습니다.',
          cause: '회차를 재개하면 분자만 리셋됐습니다.',
          action: '상태값 대신 "분모 = 분자 + 나머지" 불변식으로 걸러냈습니다.',
          result: '실제 수율은 4.2% 였습니다.',
        },
        {
          title: '200명 넘게 보낸 날 답장함이 통째로 사라진 문제',
          cause: '방 번호 200개(3.5KB)를 넣은 요청 URL 을 앞단 프록시가 502 로 끊었습니다.',
          action: '길이별로 실측해 경계를 찾고(100개 통과, 200개 실패) 60개 단위로 나눴습니다.',
        },
        {
          title: 'LLM 벤더 매칭 결과가 요청마다 달라지던 문제',
          cause: '30개씩 나눈 청크마다 같은 벤더가 다른 점수를 받고 마지막 값으로 덮였습니다. 모델이 가끔 항목을 빠뜨리기도 했습니다.',
          action: '최고 점수만 유지하고 빠진 항목만 좁혀 재질의했습니다. 후보는 지식 그래프 ∪ 카테고리 합집합으로 바꿨습니다.',
        },
      ],
      aiCollab: [
        '운영 수치: 셀러찾기 회차당 약 510명 조사 · 통과율 약 4.4%, 맞춤카톡 한 회차 261명 발송.',
        '상품 캐시는 하루 3회 동기화하고, 부분 실패로 전체 상품이 종료 처리되지 않게 비율 + 절대 하한 가드를 뒀습니다.',
        '기능마다 설계 문서 → 계획 → 테스트 먼저 → 구현 → 리뷰 순서로 진행했습니다.',
      ],
    },
    {
      id: 'company-os',
      slug: 'company-os',
      logo: '/images/logo6.png',
      title: 'AI Company OS · Spark — 사람은 승인만 하는 사내 AI 조직',
      shortTitle: 'AI Company OS · Spark',
      period: '2026.05 ~ 현재',
      role: '설계·개발·인프라·운영 (1인)',
      repos: 'styleseller-agent-company (서버·MCP·서비스) · brand-tool (Spark·승인함 화면)',
      oneLiner: '오픈소스 Paperclip(이슈·승인·예산) 위에 회사 전용 에이전트 조직과 사내 AI 비서 Spark 를 얹었습니다.',
      highlights: [
        '에이전트 조직: CEO 에이전트 아래 CS·콘텐츠·캠페인·광고 에이전트 약 20개, 매일 도는 것은 CS·콘텐츠 계열',
        'Spark: 출처를 인용하는 사내 AI 비서. 역할별 읽기 전용으로 DB 4개 조회, CEO 모드 실행 제안은 승인함으로',
        'MCP: 지식 그래프 검색·플랫폼 제어 서버 직접 개발, Google Workspace 서버 통합',
        '커머스 리서치: Spark 요청 → 직원 크롬 확장이 리뷰 수집 → VOC 분석 엑셀·PDF',
      ],
      stack: ['TypeScript', 'Node.js / Express', 'React', 'PostgreSQL (Drizzle)', 'Python / FastAPI', 'MCP', 'LiteLLM', 'Gemini 2.5', 'Claude', 'LightRAG + Neo4j', 'Langfuse', 'n8n', 'Docker Compose', 'GitHub Actions', 'GCP'],
      scale: [
        '본인 커밋 4,316개 (merge·upstream 제외)',
        '서비스 디렉터리 46개 · MCP 서버 3개 · 플러그인 2개',
        '설계 문서 56개 · 실행 계획 98개',
      ],
      background:
        '처음 계획은 Temporal·LangGraph·LiteLLM·MCP 를 모두 갖춘 5계층 스택이었습니다. 2026년 5월 20일 기준 플랫폼은 설치돼 있었지만 등록된 에이전트는 0개였습니다. ' +
        '그래서 새로 쌓는 대신, 이미 돌아가던 자산(메일 에이전트, DM 봇, n8n)을 먼저 연결하는 방향으로 바꿨습니다.',
      flow: [
        '업무는 이슈로 들어옵니다. n8n 은 트리거만 맡고, 추론이 필요한 일은 Claude Code 에이전트가, 단순 처리는 FastAPI 서비스가 맡습니다.',
        '직원은 사내 웹의 Spark 에게 묻습니다. Spark 는 역할에 맞는 읽기 전용 조회와 지식 그래프 검색으로 출처를 붙여 답합니다.',
        '실행이 필요한 제안은 승인함으로 가고, 사람이 승인해야 실행됩니다.',
      ],
      architectureImages: [
        { src: '/images/v2/company-os-ko.png', alt: 'AI Company OS 구조도' },
        { src: '/images/proj6-2.png', alt: 'AI 에이전트 조직도' },
      ],
      troubleshooting: [
        {
          title: '과설계를 버리고 동작하는 구조로 전환',
          problem: '계획한 5계층 스택은 구축 비용이 컸고, 5월 20일 기준 등록된 에이전트는 0개였습니다.',
          action: 'Temporal 은 n8n 트리거 + 이슈로, LangGraph 는 Claude Code 에이전트로 대체하고, 이미 돌아가던 자산부터 연결했습니다.',
          result: '넉 달 사이 약 20개 에이전트가 조직도에 올라갔습니다.',
        },
        {
          title: 'Spark 가 권한 밖 데이터를 보지 못하게 하는 설계',
          action: '역할은 요청 본문을 믿지 않고 서버가 DB 멤버십으로 다시 계산합니다. SQL 은 읽기 전용 역할과 안전한 SELECT 검사만 통과합니다. 승인 실행은 멱등이고, 킬 스위치가 있습니다.',
        },
        {
          title: '리뷰 1,000건 수집이 100분 걸리는 구조였던 문제',
          cause: '최소화된 창에서는 타이머가 분당 1회로 제한돼 0.5초 대기가 60초가 됐습니다. 계산상 1,000건에 100분이었습니다.',
          action: '대기를 서비스 워커가 잡는 틱으로 바꿔 타이머 제한을 받지 않게 했습니다.',
          result: '실측 1,000건 2분 30초.',
        },
        {
          title: '여러 AI 세션이 동시에 배포할 때의 안전장치',
          action: 'VM 전역 배포 락, 커밋 안 된 트리 배포 거부, 마지막 빌드 커밋 기록, 배포 대상 판정 함수 테스트를 넣었습니다.',
        },
        {
          title: 'CEO 에이전트가 Gemini 폴백으로 넘어가면 빈 답이 나오던 문제',
          problem: 'CEO 에이전트의 Claude Code 구독 로그인이 끊기면 Hermes 의 Gemini 폴백이 이어받는데, 이때 빈 답이 나왔습니다.',
          action: 'Gemini 프록시의 멀티턴 function calling 을 복원했습니다(tool_calls 복원, tool_call_id 매핑, 타임아웃 정렬).',
        },
      ],
      aiCollab: [
        '평가: Spark 회귀 평가 케이스 세트를 두고 답변 품질을 확인합니다.',
        '관측: 에이전트 경로의 LLM 호출은 LiteLLM 을 거치고 Langfuse 로 추적합니다.',
        '설계 원칙: 환불·VIP·대외 계약처럼 되돌리기 어려운 일은 사람 승인을 거칩니다.',
      ],
    },
    {
      id: 'email-agent',
      slug: 'email-agent',
      logo: '/images/logo8.png',
      title: '대표 메일 에이전트 — GraphRAG 초안 + 사람 승인',
      shortTitle: '대표 메일 에이전트',
      period: '2026.03 ~ 2026.09 (이후 사내 지식 허브로 확장)',
      role: '설계·개발·배포 (1인)',
      repos: 'email-agent (FastAPI) · styleseller-agent-company (대시보드 플러그인·knowledge-mcp)',
      oneLiner: '메일을 분류하고, 회사 지식 그래프에서 근거를 찾아 대표 말투로 초안을 쓰고, 사람이 승인해야 나갑니다. 이때 만든 지식 그래프가 회사 전체의 지식 허브가 됐습니다.',
      highlights: [
        'Gmail → n8n → FastAPI: 파싱 → 분류 → 초안 → 검증 → 학습',
        'LightRAG 지식 그래프(Neo4j + pgvector), 커버리지가 부족하면 질의를 한 번 다시 쓰는 에이전트형 검색',
        'LLM-as-Judge 품질 검증 + 아첨·앵무새 답변 검사',
        '보낸 메일과 사람 수정본으로 문체를 학습하는 스타일북',
      ],
      stack: ['Python', 'FastAPI', 'asyncio', 'LightRAG', 'Neo4j', 'PostgreSQL + pgvector', 'Vertex AI Gemini 2.5', 'Claude (2026.04–07)', 'n8n', 'Slack', 'Docker Swarm', 'pytest', 'Pyright'],
      scale: [
        '커밋 1,418개 (2026.03–09, merge 제외, 조직 저장소 기준)',
        'Python 약 4만 줄 · API 라우터 26개 · 엔드포인트 85개',
        '지식 그래프 워크스페이스를 메일·벤더 CS·Spark·벤더 매칭이 함께 사용',
      ],
      background:
        '대표 메일함에는 브랜드 제휴, 셀러 입점 문의, 협업 제안이 섞여 들어왔습니다. 답장은 과거 거래 맥락을 알아야 쓸 수 있어서 대표 한 사람에게 몰렸습니다. ' +
        '목표는 "근거 있는 초안을 먼저 만들어 두고, 사람은 확인만 한다"였습니다.',
      flow: [
        'n8n 이 새 메일을 감지해 파싱·분류를 요청합니다.',
        '지식 그래프에서 이 회사·담당자·과거 요청을 찾아 초안을 쓰고, LLM 판정기로 검증합니다.',
        '검증 뒤 Gmail 초안을 먼저 만들고, Slack 에는 통과 여부에 따라 "Draft Ready" / "Needs Review" 알림과 발송 버튼이 갑니다. 발송은 사람이 누릅니다.',
        '보낸 메일을 다시 학습해 문체와 지식을 갱신합니다.',
      ],
      architectureImages: [
        { src: '/images/v2/email-agent-ko.png', alt: '대표 메일 에이전트 파이프라인' },
      ],
      troubleshooting: [
        {
          title: '평면 벡터 검색으로는 과거 맥락을 못 찾던 문제',
          problem: '"이 회사가 전에 무엇을 물었나"를 벡터 검색만으로는 찾지 못했습니다.',
          action: 'v2 에서 LightRAG 지식 그래프로 회사·담당자·과거 요청을 관계로 묶었습니다.',
        },
        {
          title: '로컬 리랭커가 VM 메모리를 과하게 쓰던 문제',
          action: '2.2GB ONNX 리랭커를 Vertex AI Gemini 리랭킹으로 교체했습니다.',
        },
        {
          title: '행정·물류 확인 메일을 "앵무새 답변"으로 오탐하던 문제',
          action: '검증 프롬프트에 업무 맥락 예외를 넣고, 콜드 메일에도 같은 자가 검증을 적용했습니다.',
        },
      ],
      aiCollab: [
        '운영 상태: 대표 메일 자동 초안은 2026-09-02 에 멈췄습니다. 분류·보낸 메일 학습은 계속 돌고, 이때 만든 지식 그래프(워크스페이스 13개)는 카카오 CS·벤더 CS·Spark·벤더 매칭이 함께 쓰는 사내 지식 허브로 계속 운영됩니다.',
        '지식 그래프는 knowledge-mcp 를 통해 Spark·벤더 CS 에이전트가 쓰고, brand-tool 벤더 매칭이 직접 검색합니다.',
        '완료 조건: 모든 함수 타입 힌트, Pyright 에러 0, 보안 교차 검증 지적 반영.',
      ],
    },
    {
      id: 'field-fleet',
      slug: 'field-fleet',
      logo: '/images/logo9.png',
      title: '직원 PC 함대 · 운영 인프라 — 서버가 못 하는 일을 PC 에서, 안전하게',
      shortTitle: '직원 PC 함대 · 운영 인프라',
      period: '2026.02 ~ 현재',
      role: '확장·CLI·설치기·배포 파이프라인·인프라 (1인)',
      repos: 'styleseller-agent-company (설치기·릴레이·수집기·발송기·배포) · Instagram DM 확장 · brand-tool (배포)',
      oneLiner: 'API 가 없는 인스타그램·카카오톡 작업을 직원 PC 에서 돌리고, 그 PC 들을 한 줄 설치·자동 갱신·원격 관제로 운영했습니다.',
      highlights: [
        '맥·윈도우 한 줄 설치기, 관리자 권한 없이 설치, 도구마다 주기가 다른 자동 갱신',
        '카톡 실시간 릴레이(직원 11명), 윈도우 카톡 수집기, 오픈채팅 공구 공지 자동 발송',
        'Instagram DM 크롬 확장(2026.02–07): 신뢰 입력(CDP), 다단계 발송 폴백, 매일 도는 자가 점검 에이전트',
        '인프라: GCP VM, Docker Compose, 자체 호스팅 Postgres 6개, GitHub Actions → 레지스트리 배포',
      ],
      stack: ['JavaScript / Node.js', 'Chrome Extension MV3', 'Chrome DevTools Protocol', 'Swift', 'Python', 'Bash', 'PowerShell', 'launchd', 'Playwright', 'Docker', 'nginx', 'GitHub Actions', 'GCP'],
      scale: [
        '직원 PC 배포망: 커밋 689개',
        'Instagram DM 확장 + 자가 점검: 코드 2.6만 줄',
        '카톡 실시간 동기화 직원 11명 · 셀러찾기 워커 PC 9대',
      ],
      background:
        '인스타그램 DM 과 개인 카카오톡은 공식 API 가 없습니다. 직원들은 같은 문구를 복사해 붙였고, 대화 기록은 각자의 PC 에만 남았습니다. ' +
        '서버에서 돌릴 수 없는 일은 직원 PC 를 자동화 노드로 삼고, 그 PC 들을 안전하게 배포·갱신·관제하는 체계를 만들었습니다. 서버 쪽은 VM 한 대에 약 40개 서비스를 올려 운영했습니다.',
      flow: [
        '직원은 설치 한 줄로 필요한 도구 묶음을 설치합니다. 관리자 권한이 필요 없습니다.',
        '설치된 도구는 도구마다 다른 주기로 스스로 갱신합니다. 셀러찾기 워커는 잡 사이마다, 맥 카톡 릴레이는 매일 1회, 쿠팡 확장은 하루 3회입니다. 버전은 배포본 zip 의 sha256 으로 판정합니다.',
        '서버는 작업 큐와 상태 보고로 각 PC 를 관제하고, 멈추면 Slack 으로 알립니다.',
      ],
      architectureImages: [
        { src: '/images/v2/field-fleet-ko.png', alt: '직원 PC 함대와 운영 인프라 구조도' },
      ],
      troubleshooting: [
        {
          title: '클라우드 DB 가 전송량 한도로 멈춘 날',
          problem: '클라우드 DB 가 전송량 한도를 넘어 모든 API 가 멈췄습니다.',
          action: '앱이 REST 프로토콜만 쓴다는 것을 코드 전수 검색으로 확인하고, VM 에 Postgres + PostgREST + nginx 를 같은 모양으로 세웠습니다.',
          result: '환경변수 교체만으로 당일 복구했습니다.',
        },
        {
          title: '호스팅 무료 한도 정지',
          action: '정지 뒤 프로젝트 10개를 새 팀으로 옮겨 복구하고, 웹앱용 VM 배포 파이프라인(GitHub Actions → 레지스트리 → nginx 무중단 교체)을 이틀 만에 만들었습니다.',
        },
        {
          title: '배포 한 번에 45~51분 걸리던 문제',
          cause: 'VM 이 6.3GB 이미지를 매번 다시 구웠습니다.',
          action: 'CI 가 만든 이미지를 레지스트리에서 받게 바꿨습니다.',
          result: '배포 한 번이 약 11분으로 줄었습니다.',
        },
        {
          title: '오픈채팅 발송이 사흘 동안 조용히 실패한 문제',
          cause: '권한 문제가 아니라 카톡 메인 창이 없는 상태로 굳어 있었고, 실패를 알릴 경로가 없었습니다.',
          action: '발송기 재시작 후 1회 재시도, 실패 사유를 담은 Slack 알림, 발송 직후 감시 크론을 추가했습니다.',
        },
        {
          title: '사원 인증 쿠키를 손으로 만들 수 있던 보안 구멍',
          action: '엣지 미들웨어에서 Web Crypto HMAC 서명 + 만료로 교체했습니다. 비밀값이 없으면 거부합니다(fail-closed).',
        },
        {
          title: '윈도우 워커가 잡을 집고도 진행 0 — 서버가 5분마다 잡을 회수하고 같은 PC 가 다시 집던 문제',
          cause: '예외 처리 코드 안의 import 누락이었습니다. 워커 프로세스는 살아 있었고, 그 분기를 지나가는 테스트가 없어서 초록이었습니다.',
          action: '실제 프로세스를 띄워 배선을 확인하는 테스트를 추가했습니다.',
          result: '교훈: 테스트 초록 ≠ 배선 맞음.',
        },
      ],
      aiCollab: [
        '공식 API 가 없는 서비스의 자동화는 서비스 약관과 계정 안전을 먼저 확인하고, 사람의 계정·PC 에서 사람이 켜고 끌 수 있게 설계했습니다.',
        '배포본은 "이미지 날짜"가 아니라 도는 코드의 해시로 확인합니다.',
      ],
    },
  ],
  howIBuild: {
    title: 'How I Build with AI',
    intro:
      '코드는 Claude Code 세션 여러 개를 병렬로 지휘해 만듭니다. 대신 무엇을 만들지, 어디까지 자동화할지, 결과가 맞는지는 제가 정하고 확인합니다.',
    image: '/images/v2/build-loop-ko.png',
    loopTitle: '작업 루프',
    harnessTitle: '하네스 — 에이전트 실수를 규칙으로 막기',
    loop: [
      { step: '설계 문서', desc: '문제·제약·대안을 먼저 씁니다. (56개)' },
      { step: '실행 계획', desc: '단계와 단계별 검증 방법을 적습니다. (98개)' },
      { step: '테스트 먼저', desc: '재현 테스트를 쓰고 구현합니다.' },
      { step: '교차 리뷰', desc: '서로 다른 출처의 에이전트 두 개가 따로 리뷰합니다. 적대적 리뷰 한 번에 실결함 6~9개를 잡은 기록이 있습니다.' },
      { step: '실기기 확인', desc: '실제 PC·실제 화면에서 확인하고 단계적으로 배포합니다.' },
      { step: '배포 확인', desc: '도는 코드의 해시로 배포를 판정합니다.' },
    ],
    harness: [
      'CLAUDE.md·규칙 파일: 타입·RLS·비밀값·언어 등 완료 게이트',
      '사고 교훈 메모 100여 개: 같은 실수가 다음 세션에서 반복되지 않게 합니다',
      'pre-commit 훅: 손으로 말아 줄바꿈이 섞인 윈도우 배포본을 막습니다',
      '테스트 → 프로덕션 쓰기 차단 가드: 프로덕션에 닿을 수 있던 테스트 17건을 막았습니다',
    ],
    incidentsTitle: '사고에서 배운 원칙',
    incidents: [
      { title: '테스트 초록 ≠ 배선 맞음', lesson: '모킹된 테스트는 import 누락을 못 잡습니다. 실제 프로세스를 띄우는 테스트를 둡니다.' },
      { title: '한 번 못 찾은 건 없는 게 아니다', lesson: '부재를 보고하기 전에 시간 범위·검사 대상·입구와 출구를 다시 봅니다.' },
      { title: '도는 코드로 판정한다', lesson: '이미지 날짜가 아니라 실행 중인 코드의 해시로 배포를 확인합니다.' },
      { title: '되돌릴 수 없는 일괄 변환 대신 호환', lesson: '옛 형식과 새 형식을 함께 받도록 바꿉니다.' },
      { title: '지우지 말고 스위치로 끈다', lesson: '먼저 실사용 기록을 세고, 끄는 방식으로 내립니다.' },
    ],
  },
  before: {
    title: 'Before · 2024–2025',
    projects: [
      {
        route: '/projects/project5',
        logo: '/images/logo5.png',
        title: 'We:Review',
        period: '2025.08 ~ 10 · 인턴',
        oneLiner: 'OCR + LLM 영수증 검증 자동화',
        connection: '→ 반복 검수를 기계로 옮긴 첫 실무. StyleSeller 운영 자동화로 이어졌습니다.',
      },
      {
        route: '/projects/project4',
        logo: '/images/logo4.png',
        title: 'FitChecker',
        period: '2024.11 ~ 12',
        oneLiner: 'LangChain 기반 AI 홈트레이닝 챗봇 (RAG 추천)',
        connection: '→ 첫 RAG·에이전트 경험. 지식 그래프 기반 에이전트의 출발점이었습니다.',
      },
      {
        route: '/projects/project3',
        logo: '/images/logo3.png',
        title: 'Briefify',
        period: '2024.10 ~ 11',
        oneLiner: '이미지·문서 번역·요약 AI 웹 서비스',
        connection: '→ OCR·요약·번역 모델(Tesseract·T5·NLLB)을 잇는 AI 파이프라인을 처음 다뤄 봤습니다.',
      },
    ],
  },
  about: {
    title: 'About Me',
    photo: '/images/img.jpg',
    tagline: '반복 업무를 AI 시스템으로 바꾸는 AI Builder 목진희입니다.',
    paragraphs: [
      '현업에서 사람이 반복하는 일을 찾아 AI 에이전트와 자동화로 바꾸고, 배포한 뒤 운영까지 맡습니다. 반복은 기계에게, 판단은 사람에게 남기는 것이 제 원칙입니다.',
      'StyleSeller에서는 10개월 동안 혼자 사내 AI 운영 시스템을 만들었습니다. 벤더 CS 에이전트, 셀러 발굴부터 맞춤 발송까지 잇는 영업 플랫폼, 사람이 승인하는 에이전트 조직, 직원 PC 자동화를 기획부터 장애 대응까지 담당했습니다.',
      'Claude Code 에이전트 여러 개를 병렬로 지휘해 빠르게 만들고, 결과는 테스트·교차 리뷰·실기기 확인으로 검증합니다. 사고가 나면 원인과 교훈을 규칙으로 남겨 같은 실수를 반복하지 않습니다.',
      '법학을 공부하고 영어 강사와 어린이집 운영실장으로 일하면서, 현장에서 일하는 사람의 불편을 먼저 듣는 습관이 생겼습니다. 그 습관이 지금 무엇을 자동화할지 고르는 기준입니다.',
    ],
    experienceTitle: 'Journey',
    experienceLead: '법학 전공에서 AI Builder까지',
    careerChangeLabel: 'Career Change',
    experience: [
      { period: '2025.12 – 현재', org: 'StyleSeller · AI Builder (1인)', summary: '사내 AI 운영 시스템을 혼자 설계·구축·운영', kind: 'tech' },
      { period: '2025.08 – 2025.10', org: 'We:Review(Welead) 인턴', summary: 'OCR + LLM 영수증 검수 파이프라인을 혼자 구축', kind: 'tech' },
      { period: '2025.05 – 2025.07', org: '한국IT비즈니스진흥협회', summary: '생성형 AI 개발자 맞춤형 인재 양성 과정', kind: 'tech' },
      { period: '2024.10 – 2024.12', org: '하이미디어아카데미 · AI 과정', summary: '현업 멘토와 AI 프로젝트 실행 (Briefify, FitChecker)', kind: 'tech' },
      { period: '2024.04 – 2024.10', org: '하이미디어아카데미 · 풀스택 과정', summary: 'Spring Boot·Vue.js 팀 프로젝트, 협업과 버전 관리', kind: 'tech', careerChange: true },
      { period: '2022.06 – 2024.02', org: '몬테키즈 · 영어 강사', summary: '개인 맞춤형 수업과 자기주도 학습 설계', kind: 'pre' },
      { period: '2021.02 – 2023.06', org: '학점은행제 · 경영학', summary: '경영학 학위 과정', kind: 'pre' },
      { period: '2021.03 – 2022.05', org: 'Pots&Pans · 영어 강사', summary: '몰입형 수업과 학습 성과 관리', kind: 'pre' },
      { period: '2018.08 – 2020.09', org: 'JLS(정상어학원) · 강사', summary: '참여형 수업 설계와 학부모 소통', kind: 'pre' },
      { period: '2015.03 – 2018.02', org: '전원 어린이집 · 운영실장', summary: '조직 관리와 운영 전반', kind: 'pre' },
      { period: '2008.03 – 2012.02', org: '청주대학교 · 법학 학사', summary: '법학 전공', kind: 'pre' },
    ],
    nowTitle: 'Now',
    nowText: '벤더 CS 자동 답변 개선판을 검증하고, 셀러찾기 목표를 올리고, 운영 관측을 강화하고 있습니다.',
  },
  skills: {
    title: 'Skills',
    lead: '에이전트부터 배포·운영까지, 실제 서비스에 쓴 기술입니다.',
    groups: [
      {
        id: 'ai-agent',
        title: 'AI / Agent',
        items: [
          { id: 'llm-agent', label: 'Agentic RAG · 도구 호출 에이전트' },
          { id: 'mcp', label: 'MCP 서버' },
          { id: 'rag', label: 'GraphRAG (LightRAG · Neo4j · pgvector)' },
          { id: 'litellm', label: 'LiteLLM 모델 라우팅' },
          { id: 'langfuse', label: 'Langfuse 관측' },
          { id: 'hitl', label: 'HITL 승인 설계 · LLM 판정기' },
          { id: 'claude-code', label: 'Claude Code 멀티 세션' },
        ],
      },
      {
        id: 'backend',
        title: 'Backend',
        items: [
          { id: 'python', label: 'Python' },
          { id: 'fastapi', label: 'FastAPI' },
          { id: 'nextjs', label: 'Next.js' },
          { id: 'node', label: 'Node.js / Express' },
          { id: 'postgres', label: 'PostgreSQL / PostgREST' },
          { id: 'supabase', label: 'Supabase' },
          { id: 'java', label: 'Java' },
          { id: 'spring', label: 'Spring' },
          { id: 'mysql', label: 'MySQL' },
          { id: 'jpa', label: 'JPA' },
        ],
      },
      {
        id: 'frontend',
        title: 'Frontend',
        items: [
          { id: 'react', label: 'React' },
          { id: 'js', label: 'JavaScript' },
          { id: 'html', label: 'HTML' },
          { id: 'css', label: 'CSS' },
          { id: 'vue', label: 'Vue.js' },
          { id: 'flutter', label: 'Flutter' },
        ],
      },
      {
        id: 'devops',
        title: 'DevOps · Automation',
        items: [
          { id: 'docker', label: 'Docker' },
          { id: 'docker-compose', label: 'Docker Compose' },
          { id: 'gh-actions', label: 'GitHub Actions' },
          { id: 'gcp', label: 'GCP VM' },
          { id: 'nginx', label: 'nginx' },
          { id: 'zero-downtime', label: '무중단 배포' },
          { id: 'git', label: 'Git' },
          { id: 'github', label: 'GitHub' },
          { id: 'n8n', label: 'n8n' },
          { id: 'chrome-ext', label: 'Chrome Extension MV3' },
          { id: 'playwright', label: 'Playwright / CDP' },
          { id: 'swift', label: 'Swift (macOS)' },
        ],
      },
    ],
  },
  legacyProjects: {
    project1: { title: '전직시', route: '/projects/project1' },
    project2: { title: 'Flux', route: '/projects/project2' },
    project3: { title: 'Briefify', route: '/projects/project3' },
    project4: { title: 'FitChecker', route: '/projects/project4' },
    project5: { title: 'We:Review', route: '/projects/project5' },
  },
};

export default ko;
